stellar-lend/contracts/hello-world/src/lib.rs
This PR introduces a stub for the `deposit_collateral` function in the StellarLend Soroban contract. This function will serve as the entry point for users to deposit collateral into the protocol. The actual business logic will be implemented in a future PR.
- Added a public `deposit_collateral` function to the contract.
- The function accepts parameters for the depositor and amount (types are placeholders).
- Added a placeholder comment describing the intended logic.
- Added a doc comment for the function.
Closes #5  - Add deposit_collateral Function Stub to Soroban Contract
---
**Note:**  
This PR only adds the function stub. Full implementation will follow in subsequent PRs.
=> feat: Add deposit_collateral function stub to Soroban contract

stellar-lend/contracts/hello-world/src/lib.rs
This PR introduces a stub for the `borrow` function in the StellarLend Soroban contract. This function will serve as the entry point for users to borrow assets from the protocol. The actual business logic will be implemented in a future PR.
- Added a public `borrow` function to the contract.
- The function accepts parameters for the borrower and amount (types are placeholders).
- Added a placeholder comment describing the intended logic.
- Added a doc comment for the function.
Closes #7  - Add borrow Function Stub to Soroban Contract
---
**Note:**  
This PR only adds the function stub. Full implementation will follow in subsequent PRs.
=> feat: Add borrow function stub to Soroban contract

stellar-lend/contracts/hello-world/src/lib.rs
This PR introduces access control checks and input validation for all user-facing functions in the StellarLend Soroban contract. This ensures only valid and authorized actions are processed, and lays the groundwork for robust security and error handling.
- Added access control checks to deposit, borrow, repay, withdraw, and liquidate stubs.
- Added input validation for nonzero amounts and valid addresses.
- Expanded documentation and comments for all new code.
Closes #13  - Add access control and input validation scaffolding
---
**Note:**  
This PR is focused on scaffolding and does not implement business logic.
=> feat: Add access control and input validation scaffolding to contract functions

stellar-lend/contracts/hello-world/src/test.rs
This PR introduces unit tests for all user-facing functions in the StellarLend Soroban contract. It ensures the contract is robust, testable, and ready for future feature development.
- Added/expanded the test module for the contract.
- Wrote unit tests for deposit_collateral, borrow, repay, withdraw, and liquidate.
- Tested input validation (zero/negative amounts, empty addresses).
- Tested access control logic (unauthorized actions).
- Expanded documentation and comments for all new code.
Closes #15  - Add unit tests for all user-facing contract functions
---
**Note:**  
This PR is focused on testing and does not implement business logic.
=> feat: Add unit tests for all user-facing contract functions

stellar-lend/contracts/hello-world/src/lib.rs
This PR introduces the basic logic for updating user collateral and debt balances in the StellarLend Soroban contract. It updates the `Position` struct and storage logic, implements balance updates in deposit, borrow, repay, and withdraw functions, and adds helper methods for balance management.
- Updated the `Position` struct and storage logic.
- Implemented logic in `deposit_collateral`, `borrow`, `repay`, and `withdraw` to update user balances.
- Added helper methods for balance management.
- Expanded documentation and comments for all new code.
Closes #17  - Scaffold collateral and debt accounting logic
---
**Note:**  
This PR is focused on scaffolding and does not implement real asset transfers or liquidation logic.
=> feat: Scaffold collateral and debt accounting logic

stellar-lend/contracts/hello-world/src/lib.rs
This PR introduces admin and protocol configuration management to the StellarLend Soroban contract. It enables the admin to set the price oracle address and minimum collateral ratio, and enforces access control for admin-only actions. Protocol logic is updated to use dynamic, on-chain configurable parameters.
- Added `ProtocolConfig` for admin, oracle, and min collateral ratio management.
- Implemented admin-only setters and access control.
- Updated protocol logic to use dynamic, on-chain configurable parameters.
- Expanded documentation and comments.
Closes #23  - Add admin and protocol configuration logic
---
**Note:**  
This PR is focused on scaffolding protocol configuration and does not implement real oracle integration.
=> feat: Add admin and protocol configuration logic

stellar-lend/contracts/hello-world/src/lib.rs
This PR introduces user-facing view/query functions to the StellarLend Soroban contract. These functions allow users and frontends to query protocol state, such as their position, protocol parameters, and system-wide stats.
- Added a function to query a user's position (collateral, debt, ratio).
- Added functions to query protocol parameters (admin, oracle address, min collateral ratio).
- Added a function to query system-wide stats (total collateral, total debt).
- Expanded documentation and comments for all new code.
Closes #25  - Add user-facing view/query functions
---
**Note:**  
This PR is focused on read/view logic and does not change protocol state.
=> feat: Add user-facing view/query functions for positions and protocol state

stellar-lend/contracts/hello-world/src/lib.rs, stellar-lend/contracts/hello-world/src/test.rs, stellar-lend/contracts/hello-world/test_snapshots/test/test_pause_switches_admin_functions.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_risk_config_initialization.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_risk_params_admin_functions.1.json
This PR introduces a comprehensive risk management system and advanced liquidation logic to the StellarLend DeFi lending protocol smart contract. The changes are designed to improve protocol safety, flexibility, and transparency for both users and administrators.
---
- **RiskConfig Struct**: Stores protocol risk parameters, including:
- `close_factor`: Max % of debt that can be repaid in a single liquidation (partial liquidation support).
- `liquidation_incentive`: Bonus % of collateral awarded to liquidators.
- Pause switches for protocol actions: `pause_borrow`, `pause_deposit`, `pause_withdraw`, `pause_liquidate`.
- **Admin Functions**:
- `set_risk_params`: Admin can update `close_factor` and `liquidation_incentive`.
- `set_pause_switches`: Admin can pause/unpause core protocol …
=> Implement Advanced Risk Management & Liquidation Enhancements

stellar-lend/contracts/hello-world/src/lib.rs, stellar-lend/contracts/hello-world/src/test.rs, stellar-lend/contracts/hello-world/test_snapshots/test/test_reserve_management_initialization.1.json
This PR introduces a comprehensive Reserve Management and Protocol Revenue system to the StellarLend DeFi smart contract. The new system enables the protocol to collect, manage, and distribute protocol fees, track reserves, and provide robust treasury management and analytics.
---
- **ReserveData & RevenueMetrics Structs**: New data structures for tracking protocol fees, reserves, treasury address, and revenue analytics.
- **Protocol Fee Collection**: Automatic collection of protocol fees from interest payments (borrow and supply), based on the reserve factor.
- **Reserve Accumulation & Utilization**: Accumulates protocol reserves and enables admin-controlled utilization for protocol stability.
- **Treasury Management**:
- Configurable treasury address (admin only).
- Manual and emergency …
=> Feat: Implement Reserve Management & Protocol Revenue System

stellar-lend/contracts/hello-world/src/lib.rs, stellar-lend/contracts/hello-world/src/test.rs
This PR introduces a lightweight user activity tracking and analytics system to the StellarLend protocol. It enables tracking of user actions (deposits, withdrawals, borrows, repayments), aggregates protocol-wide activity statistics, and provides query functions for both user and protocol analytics.
- **User Activity Tracking**
- Tracks total deposits, withdrawals, borrows, repayments, last activity timestamp, and activity count per user.
- New function: `track_user_activity()` to record user actions.
- New function: `get_user_activity()` to query user activity metrics.
- New function: `get_recent_activity()` to fetch the most recent user action.
- **Protocol Analytics**
- Tracks total users, active users (24h/7d), total transactions, and last update timestamp.
- New function: …
=> ✨ feat: Add User Activity Tracking & Protocol Analytics

stellar-lend/contracts/hello-world/src/lib.rs, stellar-lend/contracts/hello-world/src/test.rs
This PR implements foundational governance features by supporting multiple protocol administrators, admin role management, and event logging. This enables decentralized protocol control and prepares for future DAO upgrades.
- **Multi-Admin Support**: Store and manage multiple protocol administrators
- **Admin Role Management**: Add, remove, and transfer admin roles
- **Authorization Control**: Only existing admins can modify admin roles
- **Event Logging**: All admin changes are logged via events
- `add_admin(admin: Address, new_admin: Address)` - Add a new admin (admin-only)
- `remove_admin(admin: Address, remove_admin: Address)` - Remove an admin (admin-only)
- `transfer_admin(admin: Address, new_admin: Address)` - Transfer admin role (admin-only)
- `get_admins()` - Get list of all …
=> feat: Add multi-admin support and role management for basic governance

stellar-lend/contracts/hello-world/src/lib.rs, stellar-lend/contracts/hello-world/src/test.rs
=> feat: Add permissionless market listing system for asset proposals

stellar-lend/contracts/hello-world/src/lib.rs
this is how i implemented the  comprehensive security features and protections
1. Reentrancy Protection
A ReentrancyGuard struct was added, implementing a simple mutex pattern using contract storage.
Each core protocol function (deposit_collateral, borrow, repay, withdraw) calls ReentrancyGuard::enter(&env)?; at the start and ReentrancyGuard::exit(&env); at the end.
This ensures that if a function is re-entered before the previous call completes, the contract will detect it and abort, preventing reentrancy attacks.
2. Access Controls
Admin-only functions (such as setting protocol parameters) use ProtocolConfig::require_admin(&env, &caller_addr)?; to ensure only the admin can execute them.
User actions check if the account is frozen using FrozenAccounts::is_frozen(&env, &user_addr), …
=> implementation of comprehensive security features and protections

stellar-lend/contracts/hello-world/src/lib.rs
closes issue: #75 
- Implemented on-chain KYC status tracking and enforcement for all user-facing functions.
- Added blacklist storage and enforcement; blacklisted users are blocked from protocol actions.
- Integrated AML event emission for large/suspicious transactions.
- Added query stubs for compliance reporting and regulatory monitoring.
=> feat: added on-chain compliance (KYC, AML, Blacklisting, Reporting)

.github/workflows/ci-cd.yml
=> Feat: Implement CI/CD Pipeline with Cargo Build and Test

stellar-lend/contracts/hello-world/src/lib.rs
This PR implements comprehensive advanced user experience features for the StellarLend protocol, addressing issue #97. The implementation includes batch operations, gas optimization strategies, user-friendly error messages, transaction simulation capabilities, and enhanced usability features.
- **Multi-transaction Processing**: Execute multiple operations in a single transaction
- **Operation Types**: Support for Deposit, Withdraw, Borrow, Repay, and Liquidate operations
- **Efficient Grouping**: Operations are automatically grouped by type for optimal execution
- **Batch Validation**: Comprehensive validation of batch parameters before execution
- **Result Tracking**: Detailed results for each operation in the batch
- **Multiple Strategies**: 
- `BatchSimilar`: Group similar operations
- …
=> feat: Implement Advanced UX Features - Batch Operations, Gas Optimization, and User-Friendly Interfaces

stellar-lend/Cargo.lock, stellar-lend/contracts/hello-world/Cargo.toml, stellar-lend/contracts/hello-world/src/lib.rs, stellar-lend/contracts/hello-world/src/test.rs, stellar-lend/contracts/hello-world/test_snapshots/test/test_borrow_insufficient_collateral_ratio.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_borrow_success.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_contract_already_initialized.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_contract_initialization.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_deposit_collateral.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_deposit_collateral_invalid_address.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_deposit_collateral_invalid_amount.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_get_position_not_found.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_get_protocol_params.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_get_system_stats.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_liquidate_not_eligible.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_liquidate_success.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_repay_full_amount.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_repay_success.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_set_pause_switches.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_set_risk_params.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_set_risk_params_unauthorized.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_withdraw_insufficient_collateral.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_withdraw_insufficient_collateral_ratio.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_withdraw_success.1.json
This MR addresses critical compatibility issues with the Soroban SDK and ensures all build and test operations pass successfully. The changes focus on making the StellarLend smart contracts fully compatible with the Stellar blockchain's Soroban smart contract platform.
- **Vec Operations**: Fixed `Vec::new()` calls to include required `Env` parameter and changed `Vec::push()` to `Vec::push_back()`
- **String Handling**: Resolved type mismatches between `alloc::string::String` and `soroban_sdk::String`
- **Symbol Usage**: Replaced deprecated `Symbol::short()` with `Symbol::new()` throughout the codebase
- **Storage Access**: Updated all storage key functions to use actual `Env` parameter instead of `Env::default()`
- **Module Integration**: Properly included `test.rs` as a module in …
=>  Fix Soroban SDK compatibility issues and ensure all tests pass

stellar-lend/contracts/hello-world/src/lib.rs
Adds cross-asset position support so users can deposit multiple assets as collateral and borrow any supported asset against total collateral value. Preserves existing single-asset behavior.
- Data structures:
- `AssetParams` (collateral factor, feature toggles)
- `CrossPosition` (per-asset collateral and debt maps)
- Storage:
- Asset params map
- Oracle prices map
- Cross positions map
- Cross-asset APIs:
- Admin: `set_asset_params`, `set_asset_price`
- User: `deposit_collateral_asset`, `borrow_asset`, `repay_asset`, `withdraw_asset`
- Views: `get_cross_position_summary` (weighted collateral value, total debt, ratio)
- Events:
- `CrossDeposit`, `CrossBorrow`, `CrossRepay`, `CrossWithdraw`
- Risk/ratio:
- Weighted collateral = sum(collateral_i * price_i * collateral_factor_i)
- Total debt …
=> feat: Implement Cross-Asset Collateralization and Borrowing

stellar-lend/contracts/hello-world/src/lib.rs
Introduces a flash loan mechanism allowing users to borrow within a single transaction with a fee, requiring callback execution and atomic repayment.
- Admin-configurable fee:
- `set_flash_loan_fee_bps` (default 5 bps = 0.05%)
- Flash loan API:
- `flash_loan(initiator, asset, amount, receiver_contract)`
- Invokes receiver at `on_flash_loan(asset, amount, fee, initiator)`
- Events:
- `FlashLoanInitiated`, `FlashLoanCompleted`
- Safety:
- Reentrancy guard on entrypoint
- Atomicity via contract invocation; receiver reverts on failure
- Token flow and accounting kept abstract for now (integration stub); intended for integrations to enforce repayment inside callback.
- Validates asset presence via price registry as a proxy for “supported asset”.
- `cd stellar-lend`
- `cargo build && cargo …
=> feat: Add Flash Loan Entry Point with Fee and Callback (#85)

stellar-lend/contracts/hello-world/src/lib.rs
Introduces AMM registry and call-through entrypoints for swaps and liquidity operations, enabling protocol-level integrations with external DEX pools.
- Registry:
- `PairKey` for deterministic (asset_a, asset_b) pool mapping
- Admin: `set_amm_pool(asset_a, asset_b, pool)`
- AMM operations:
- `amm_swap(user, asset_in, amount_in, asset_out, min_out)` with slippage protection
- `amm_add_liquidity(user, asset_a, amt_a, asset_b, amt_b)`
- `amm_remove_liquidity(user, pool, lp_amount)`
- Events:
- `AMMSwap`, `AMMLiquidityAdded`, `AMMLiquidityRemoved`
- Execution:
- Uses `env.invoke_contract` to call `swap`, `add_liquidity`, `remove_liquidity` on registered pools
- Asset transfers and pool-specific token mechanics are abstracted; this PR provides interface-level integration only.
- Designed to be …
=> feat: AMM Integration Scaffolding and Registry (#87)

PR-102.md, PR-60.md, stellar-lend/contracts/hello-world/src/lib.rs
Introduces compliance scaffolding including KYC status registry, compliance alerts, and corresponding events.
- KYC map with admin setters: `set_kyc_status`, view: `get_kyc_status`.
- Generic compliance event logging: `report_compliance_event`.
- Events: `ComplianceKycUpdated(user, status)`, `ComplianceAlert(user, code)`.
- Intentionally modular to plug into external KYC/AML providers and reporting pipelines.
Closes #101
=> feat: Add Advanced Compliance and Regulatory Features (#101)

PR-102.md, PR-60.md, stellar-lend/contracts/hello-world/src/lib.rs
Adds security logging primitives for bug reports and audit trail events.
- Bug report logging: `log_bug_report(reporter, code)`.
- Audit trail logging: `log_audit_event(action, reference)`.
- Events: `BugReportLogged(reporter, code)`, `AuditTrail(action, ref)`.
- Hooks are ready for integration with bounty programs and audit backends.
Closes #98
=> feat: Implement Advanced Security Features and Auditing (#98)

PR-102.md, PR-60.md, stellar-lend/contracts/hello-world/src/lib.rs, stellar-lend/contracts/hello-world/src/oracle.rs
Enhances the oracle aggregator with multiple modes, basic outlier handling, and performance tracking.
- Aggregation modes: median (default, with outlier trim) and TWAP average; admin sets via `oracle_set_mode`.
- Heartbeat TTL filtering retained; performance counter incremented per aggregation.
- Oracle module extended to support these features.
- Easily extendable with more validation (e.g., deviation checks, source scoring).
Closes #96
=>  feat: Implement Advanced Oracle Integration and Price Discovery (#96)

PR-102.md, PR-60.md, stellar-lend/contracts/hello-world/src/governance.rs, stellar-lend/contracts/hello-world/src/lib.rs, stellar-lend/contracts/hello-world/src/oracle.rs
Extends governance with delegation support and exposes delegation entrypoints.
- Governance delegation: `delegate(from -> to)`, `get_delegate(from)` in governance module.
- Contract entrypoints: `gov_delegate`, `gov_get_delegate`.
- Keeps proposals/voting/queue/execute intact.
- Ready to evolve into quadratic voting and token-based power calculations.
Closes #94
=>  feat: Implement Advanced Governance Mechanisms (#94)

PR-102.md, PR-60.md, stellar-lend/contracts/hello-world/src/governance.rs, stellar-lend/contracts/hello-world/src/lib.rs, stellar-lend/contracts/hello-world/src/oracle.rs
Adds insurance parameter storage, circuit breaker control, and claim filing events.
- Insurance params: `set_insurance_params(premium_bps, coverage_cap)`, view: `get_insurance_params()`.
- Circuit breaker: `set_circuit_breaker(flag)`, view: `is_circuit_breaker()`.
- Claim filing: `file_insurance_claim(user, amount, reason)`.
- Events: `InsuranceParamsUpdated`, `CircuitBreaker`, `ClaimFiled`.
- Intended as primitives for more complete pool accounting and payout logic.
Closes #93
=>  feat: Add Protocol Insurance and Safety Mechanisms (#93)

stellar-lend/contracts/hello-world/src/lib.rs, stellar-lend/contracts/hello-world/src/test.rs, stellar-lend/contracts/hello-world/test_snapshots/test/test_borrow_insufficient_collateral_ratio.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_borrow_success.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_contract_already_initialized.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_contract_initialization.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_deposit_collateral.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_deposit_collateral_invalid_address.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_deposit_collateral_invalid_amount.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_emergency_fund_management.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_emergency_param_updates_apply.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_emergency_pause_blocks_deposit.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_get_position_not_found.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_get_protocol_params.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_get_system_stats.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_liquidate_success.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_recovery_mode_allows_repay_blocks_borrow.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_repay_full_amount.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_repay_success.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_set_pause_switches.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_set_risk_params_unauthorized.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_withdraw_insufficient_collateral.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_withdraw_insufficient_collateral_ratio.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_withdraw_success.1.json
**Description:**
- Introduced on-ledger user roles, verification statuses, and per-user limits.
- Gated deposit, borrow, repay, withdraw, and liquidate flows behind verification and limit checks.
- Added entrypoints to manage roles, verifications, limits, and freezes.
- Emitted dedicated user-management events and updated tests to verify users before interactions.
Closes #64
=> Add advanced user management features

stellar-lend/contracts/hello-world/src/lib.rs, stellar-lend/contracts/hello-world/src/test.rs, stellar-lend/contracts/hello-world/test_snapshots/test/test_borrow_insufficient_collateral_ratio.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_borrow_success.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_contract_already_initialized.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_contract_initialization.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_deposit_collateral.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_deposit_collateral_invalid_address.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_deposit_collateral_invalid_amount.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_emergency_fund_management.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_emergency_param_updates_apply.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_emergency_pause_blocks_deposit.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_event_summary_updates.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_get_position_not_found.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_get_protocol_params.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_get_system_stats.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_liquidate_not_eligible.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_liquidate_success.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_recovery_mode_allows_repay_blocks_borrow.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_repay_full_amount.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_repay_success.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_set_pause_switches.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_set_risk_params.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_set_risk_params_unauthorized.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_withdraw_insufficient_collateral.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_withdraw_insufficient_collateral_ratio.1.json, stellar-lend/contracts/hello-world/test_snapshots/test/test_withdraw_success.1.json
**Description:**
- Added on-ledger event indexing, aggregation, and summary storage.
- Instrumented `ProtocolEvent::emit` to capture metadata for all variants and emit fallback events for previously skipped cases.
- Exposed entrypoints to retrieve event summaries, aggregates, and filtered event logs.
- Extended tests to validate the new event analytics and refreshed snapshots with expanded event data.
Closes #65
=> Enhance event system with comprehensive tracking

.claude/settings.local.json, stellar-lend/contracts/hello-world/src/amm.rs, stellar-lend/contracts/hello-world/src/lib.rs, stellar-lend/contracts/hello-world/test_snapshots/amm/tests/test_execute_swap.1.json, stellar-lend/contracts/hello-world/test_snapshots/amm/tests/test_liquidation_swap_hook.1.json, stellar-lend/contracts/hello-world/test_snapshots/amm/tests/test_pair_normalization.1.json, stellar-lend/contracts/hello-world/test_snapshots/amm/tests/test_register_amm_pair.1.json, stellar-lend/contracts/hello-world/test_snapshots/amm/tests/test_register_duplicate_pair_fails.1.json, stellar-lend/contracts/hello-world/test_snapshots/amm/tests/test_swap_history_tracking.1.json
- Closes: #166 
---
I have successfully implemented **AMM Registry and Swap Hooks (MVP)** for the StellarLend protocol. Here's what was accomplished:
---
- `AssetPair` structure to track asset pairs with AMM and pool addresses
- `PairKey` for normalized storage (ensures A < B ordering)
- `AMMStorage` for persistent storage management
- Pair registration, activation/deactivation functionality
- `liquidation_swap_hook()` - Swaps seized collateral to debt asset during liquidation
- `deleverage_swap_hook()` - Allows users to reduce debt by swapping assets
- Both hooks automatically update user positions (collateral/debt balances)
- `AMMSwap` event for tracking swap operations
- `AMMLiquidityAdded` event for pair registrations
- Integrated with existing `ProtocolEvent` system
- …
=> Feat: AMM Registry and Swap Hooks

stellar-lend/contracts/hello-world/src/lib.rs, stellar-lend/contracts/hello-world/src/liquidate.rs, stellar-lend/contracts/hello-world/src/test.rs, stellar-lend/contracts/hello-world/test_snapshots/test/test_liquidate_slippage_protection_triggers.1.json
Fixes #177 
Liquidations
Added min-out parameter
AMM (swap) (tried but failed)
Added a minimal AMM implementation and contract entrypoints
=> introduce min out params for swap
